/* ====================================================================
 * lsecompat.h - Master Unified Compatibility Umbrella Header
 * Automatically generated by create_master_header.sh
 * Install to: /usr/local/lse/include/lsecompat.h
 * ==================================================================== */

#ifndef LSECOMPAT_MASTER_H
#define LSECOMPAT_MASTER_H

/* Standard feature macro overrides for GNU / POSIX compatibility */
#ifndef _GNU_SOURCE
#  define _GNU_SOURCE 1
#endif

/* Individual Modular Compatibility Headers */
#include <lse/strtoimax_compat.h>
#include <lse/ftello_compat.h>
#include <lse/snprintf_compat.h>
#include <lse/getprogname_compat.h>
#include <lse/map_compat.h>
#include <lse/math_compat.h>
#include <lse/usleep_compat.h>
#include <lse/utimes_compat.h>
#include <lse/vterm_compat.h>

#endif /* LSECOMPAT_MASTER_H */
