/* ====================================================================
 * lsenet.h - Master Unified Compatibility Umbrella Header
 * Automatically generated by create_master_header.sh
 * Install to: /usr/local/lse/include/lsenet.h
 * ==================================================================== */

#ifndef LSENET_MASTER_H
#define LSENET_MASTER_H

/* Standard feature macro overrides for GNU / POSIX compatibility */
#ifndef _GNU_SOURCE
#  define _GNU_SOURCE 1
#endif

/* Individual Modular Compatibility Headers */
#include <lse/socket_compat.h>
#include <lse/dns_rfc2553_compat.h>

#endif /* LSENET_MASTER_H */
