#!/bin/sh
# create_master_header.sh - Unified generator for master umbrella headers
# Usage: ./create_master_header.sh <-build-lsecompat | -build-lsenet>

# Enforce mandatory first parameter check matching the build script pattern
if [ "$1" != "-build-lsecompat" ] && [ "$1" != "-build-lsenet" ]; then
    echo "Error: Missing or invalid target parameter."
    echo "Usage: $0 <-build-lsecompat | -build-lsenet>"
    exit 1
fi

TARGET="$1"

# Configure output filenames, header guards, and file arrays based on target
if [ "$TARGET" = "-build-lsecompat" ]; then
    out_file="lsecompat.h"
    guard_macro="LSECOMPAT_MASTER_H"

    HEADER_FILES="strtoimax_compat.h ftello_compat.h snprintf_compat.h dlfn_compat.h getprogname_compat.h map_compat.h math_compat.h usleep_compat.h utimes_compat.h vterm_compat.h"
else
    out_file="lsenet.h"
    guard_macro="LSENET_MASTER_H"
    HEADER_FILES="socket_compat.h dns_rfc2553_compat.h"
fi

echo "Generating $out_file..."

cat << EOF > "$out_file"
/* ====================================================================
 * $out_file - Master Unified Compatibility Umbrella Header
 * Automatically generated by create_master_header.sh
 * Install to: /usr/local/lse/include/$out_file
 * ==================================================================== */

#ifndef $guard_macro
#define $guard_macro

/* Standard feature macro overrides for GNU / POSIX compatibility */
#ifndef _GNU_SOURCE
#  define _GNU_SOURCE 1
#endif

/* Individual Modular Compatibility Headers */
EOF

for file_name in $HEADER_FILES; do
    [ -f "$file_name" ] || { echo "Warning: Header $file_name not found!"; continue; }

    echo "Aggregating $file_name"
    echo "#include <lse/${file_name}>" >> "$out_file"
done

echo "" >> "$out_file"
echo "#endif /* $guard_macro */" >> "$out_file"

echo "Done! Generated $out_file successfully."
